# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='guest', max_length=50)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
            ],
        ),
    ]
